<?php

namespace Database\Seeders;

use App\Models\Document;
use App\Models\DocumentTypes;
use Illuminate\Database\Seeder;

class DocumentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currentDate = date('Y-m-d');
        $nextReviewDate = date('Y-m-d', strtotime('+180 days', strtotime($currentDate)));

        DocumentTypes::create([
            'id' => 2,
            'name' => 'نماذج سياسات الأمن السيبراني',
            'icon' => 'fas  fa-lock',
        ]);
        DocumentTypes::create([
            'id' => 3,
            'name' => 'معايير الأمن السيبراني',
            'icon' => 'fas  fa-lock',
        ]);
        DocumentTypes::create([
            'id' => 4,
            'name' => 'الاجراءات',
            'icon' => 'fas fa-bug',
        ]);
        DocumentTypes::create([
            'id' => 8,
            'name' => 'صمود الأمن السيبراني',
            'icon' => 'fas fa-unlink',
        ]);

        Document::create([
            'id' => 2,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'السياسة العامة للأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 2,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '11',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 3,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة الالتزام بتشريعات وتنظيمات الأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 3,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '35',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 4,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة الإعدادات والتحصين',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 4,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '28,34',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 5,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة الحماية من البرمجيات الضارة',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 5,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '76',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 6,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة أمن الخوادم',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 6,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '76,125',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 7,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة أمن الشبكات',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 7,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '93,96,103',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 8,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة أمن البريد الإلكتروني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 8,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '84',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 9,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة أمن أجهزة المستخدمين والأجهزة المحمولة والأجهزة الشخصية',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 9,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '76,105',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 10,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة الاستخدام المقبول للأصول',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 10,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '63',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 11,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة مراجعة وتدقيق الأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 1,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '37',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 12,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة إدارة هويات الدخول والصلاحيات',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 12,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '67',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 13,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة الأمن السيبراني للموارد البشرية',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 13,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '40',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 14,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة إدارة سجلات الأحداث ومراقبة الأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 14,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '149',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 15,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة إدارة حزم التحديثات والإصلاحات',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 15,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '81',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 16,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة الأمن السيبراني المتعلّق بالأطراف الخارجية',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 16,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '192,199',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 17,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'أدوار ومسؤوليات الأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 17,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '15,40',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 18,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'الوثيقة المنظمة للجنة الإشرافية للأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 18,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '10',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 19,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة اختبار الاختراق',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 19,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '61,143,148',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 20,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة إدارة الثغرات',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 20,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '134,137,141',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 21,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة إدارة حوادث وتهديدات الأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 21,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '157,158,161,162,163,164,165',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 22,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة أمن قواعد البيانات',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 22,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '12,82',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 23,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة حماية تطبيقات الويب',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 23,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '100,176,179,180,182,184',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 24,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'استراتيجية الأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 24,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '5',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 25,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'الهيكل التنظيمي للأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 25,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '8',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 26,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة الأمن السيبراني لأنظمة التحكم الصناعي',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 26,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '208,212,213,215,217,218,221',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 27,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة التشفير',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 27,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '120,121,123,126',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 31,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة إدارة مخاطر الأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 31,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '17',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 32,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة الأمن السيبراني المتعلق بالحوسبة السحابية والاستضافة',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 32,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '201,204,205,206',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 33,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة الأمن السيبراني ضمن استمرارية الأعمال',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 33,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '185,845',
            'framework_ids' => '1,5',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 34,
            'document_type' => 2,
            'privacy' => 2,
            'document_name' => 'سياسة الأمن السيبراني المتعلق بالأمن المادي',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 34,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '167',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 35,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار أمن الشبكات',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 35,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '93',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 36,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار حماية البريد الإلكتروني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 36,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '13,84',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 37,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار إدارة سجلات الأحداث ومراقبة الأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 37,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '13,149',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 38,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار الحماية من البرمجيات الضارة',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 38,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '79',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 39,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار أمن أجهزة المستخدمين',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 39,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '76',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 40,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار أمن الأجهزة المحمولة',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 40,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '13,105',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 41,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار أمن الخوادم',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 41,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '76',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 42,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار أمن قواعد البيانات',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 42,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '76',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 43,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار إدارة الثغرات',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 43,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '134',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 44,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار إدارة حوادث وتهديدات الأمن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 44,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '158',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 45,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار اختبار الاختراق',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 45,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '143',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 46,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار التطوير الآمن للتطبيقات',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 46,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '30',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 47,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار حماية تطبيقات الويب',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 47,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '176',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 48,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار التشفير',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 48,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '120',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 49,
            'document_type' => 3,
            'privacy' => 2,
            'document_name' => 'معيار أمن الشبكات اللاسلكية',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 49,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '93',
            'framework_ids' => '1',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
        Document::create([
            'id' => 54,
            'document_type' => 8,
            'privacy' => 1,
            'document_name' => 'لوائح صمود الامن السيبراني',
            // 'document_status' => 3,
            'document_status'=>1,
            // 'file_id' => 65,
            'creation_date' => $currentDate,
            'last_review_date' => $currentDate,
            'review_frequency' => 180,
            'next_review_date' => $nextReviewDate,
            // 'approval_date' => $currentDate,
            'control_ids' => '138,284',
            'framework_ids' => '1,4',
            'document_owner' => 1,
            // 'document_reviewer' => NULL,
            'additional_stakeholders' => '',
            'team_ids' => '',
            'created_by' => 1
        ]);
    }
}
